### PR TITLE
Now we have a instruction to build the vignettes locally! depends on …

### PR DESCRIPTION
**Pull request by lf-araujo**
…devtools :(

### CODE REVIEW

**Comment by RMKirkpatrick** [comment]
FWIW, the _Writing R Extensions_ [manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Writing-package-vignettes) says that base R supports building vignettes with Sweave.  However, all(?) of our vignettes at this time are written in R Markdown, and I am not sure Sweave supports that format.

**Comment by eddelbuettel** [comment]
@RMKirkpatrick No magic: when you use RMarkdown, the 'vvignette driver' becomes usually the knitr and rmarkdown pair and that is declared at the DESCRIPTION level via `VignetteBuilder: knitr` with an additional `Suggests: rmarkdown`. Lots of packages have been doing this for years. (Also note that just saying `R Markdown` does not specify if you use html vignettes (popular with some) or pdf vignettes (popular with others).  I for one use a lot of pdf vignettes _which I premake locally via the standard `Rscript -e 'rmarkdown::render(filename)'`.  One can then include such pdf vignettes in Sweave vignettes (!!) without any additional tools (besides what Base R alread has, and of course a working latex installation).  I like that.

@lf-araujo I saw the thread on the list but couldn't find fine to pipe in. You never "need to" depend on `devtools` as that is not a recommended / base R package.  Very few things outside that set are mentioned in _Writiing R Extensions_.

**Comment by RMKirkpatrick** [comment]
@eddelbuettel Thank you for your informative remarks!

**Comment by lf-araujo** [comment]
@RMKirkpatrick this commit is not necessary (sorry for taking this long to look into it). It is already built into the package, following exactly @eddelbuettel suggestions. One just needs to `make html `, and the cran version will be built with vignettes and packaged. Silly me not understanding how R packaging works, sorry.

**Pull request closed without merging**
