### PR TITLE
Update PKG_LIBS and PKG_CXXFLAGS for StanHeaders compatibility

### PR DESCRIPTION
**Pull request by andrjohns**
This PR updates the Makefile generation to include the flags from `StanHeaders` and `RcppParallel`, which will be needed for the next version

### CODE REVIEW

**Comment by mhunter1** [comment]
My understanding is that CRAN does not allow syntax like

```
$(shell ${R_HOME}/bin/Rscript -e "StanHeaders:::CxxFlags()")
```

in the Makevars/Makevars.in/Makevars.win files.  From what I understand, these belong in the configure/configure.win files.

@andrjohns Do you have knowledge/experience to the contrary?

**Comment by andrjohns** [comment]
It's fine as long as you include `GNU make` in your `SystemRequirements`. It's also the approach recommended by the RcppParallel package: https://rcppcore.github.io/RcppParallel/#r_packages

**Comment by bgoodri** [comment]
Since this has been merged, can you release it to CRAN this week, so that we can release the StanHeaders that has been years in the making but is still years behind the current Stan development branch?

**Comment by andrjohns** [comment]
Would it be much trouble to submit a new CRAN release with these changes included soon? Minimising the number of downstream failures will greatly help with CRAN acceptance for the next StanHeaders

**Comment by jpritikin** [comment]
I submitted v2.21.4 with your changes on Mar 23. I'm not sure why the submission is delayed. You might inquiry on CRAN-submissions@R-project.org

**Comment by andrjohns** [comment]
Looking at the CRAN submission queue (via `cransays::take_snapshot()`) OpenMx 2.21.4 was rejected on the 23rd, unfortunately

**Comment by jpritikin** [comment]
Oh, I didn't know about `cransays`. If this is accurate information, I'm not sure what to do. I don't know why it was rejected. Should I submit it again?

**Comment by andrjohns** [comment]
You can also verify this by checking CRAN's `/incoming` FTP server itself, which has OpenMx 2.21.4 in the archive folder: https://cran.r-project.org/incoming/archive/

[Which denotes](https://r-hub.github.io/cransays/articles/dashboard.html#cran-review-workflow):
> archive: your package has been rejected from CRAN because it did not pass checks cleanly and the problems were not likely to be false positives.

So I'd suggest re-running `R CMD CHECK` to see if anything stands out (and double-checking for a failure notification from CRAN) and then trying the resubmission

**Comment by andrjohns** [comment]
I had a look at the automated failures of OpenMx from the [pretest folder](https://win-builder.r-project.org/incoming_pretest/OpenMx_2.21.5_20230401_181306/). The 'significant warning' on the debian check:
```
* checking whether package ‘OpenMx’ can be installed ... [12m/12m] WARNING
Found the following significant warnings:
  /home/hornik/tmp/R/include/R_ext/Complex.h:60:5: warning: anonymous structs are a GNU extension [-Wgnu-anonymous-struct]
```

Has since been [patched to be ignored](https://github.com/wch/r-source/commit/20fae2f4e85133281cebdb9ddb654af534e8d66e) and other packages which submitted today and received the same warning did not fail, so I believe if you resubmit OpenMx it should pass the automated checks

**Comment by jpritikin** [comment]
I submitted 2.21.5 on Apr 01. cransays shows that it was already archived. Are you sure that `archived` means that the package won't be reconsidered?

We always have trouble passing cran checks because of
```
Flavor: r-devel-linux-x86_64-debian-gcc
Check: examples, Result: NOTE
  Examples with CPU time > 2.5 times elapsed time
                           user system elapsed ratio
  mxExpectationStateSpace 1.092  0.000   0.364 3.000
  mxParametricBootstrap   1.731  0.048   0.614 2.897
```
However, I am certain that we don't use multiple threads in these tests. I can't figure out what is going on.

**Comment by jpritikin** [comment]
Okay, v2.21.6 is submitted.

**Comment by jpritikin** [comment]
Are you sure about what `archived` means? v2.21.6 is already archived.

**Comment by andrjohns** [comment]
I'm just quoting CRAN's own documentation, so feel free to either disregard or follow-up with CRAN. I don't have any more information than what they've published

**Pull request merged**
